# Generated by Django 3.2.11 on 2022-04-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
