# Generated by Django 4.0.3 on 2022-05-10 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_card_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='tour_id',
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.country'),
        ),
        migrations.AddField(
            model_name='hotelorders',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.hotels'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.city'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.city'),
        ),
        migrations.AddField(
            model_name='tourorders',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.tour'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotelorders',
            name='order_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tourorders',
            name='order_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
