# Generated by Django 4.0.3 on 2022-05-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_hotels_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.city'),
        ),
    ]
