# Generated by Django 4.0.3 on 2022-05-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_hotels_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='city',
            new_name='city_id',
        ),
    ]
