# Generated by Django 4.0.3 on 2022-05-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_city_id_hotels_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='tour',
        ),
    ]
