# Generated by Django 4.0.3 on 2022-05-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_hotels_city_hotels_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='description',
            new_name='hotel_description',
        ),
    ]
