# Generated by Django 4.0.3 on 2022-05-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_description_hotels_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='city',
            field=models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.city'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='tour',
            field=models.ForeignKey(blank=True, db_column='tour_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.tour'),
        ),
    ]
