# Generated by Django 4.0.3 on 2022-05-11 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_hotelorders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_month',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='card',
            name='card_year',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
