# Generated by Django 4.0.3 on 2022-05-11 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_card_card_month_card_card_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_year',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2021)]),
        ),
    ]
