# Generated by Django 4.0.3 on 2022-05-07 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_city_country_hotelorders_hotels_tour_tourorders_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hotelorders',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hotels',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tourorders',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='card_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbapp.card'),
        ),
    ]
