# Generated by Django 4.0.3 on 2022-05-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hotelorders',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hotels',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tourorders',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
