# Generated by Django 4.0.3 on 2022-05-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0005_alter_card_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.RemoveField(
            model_name='users',
            name='card_id',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
